services:

  db-postgres:
    image: postgres:16-alpine 
    container_name: db-postgres
    restart: always
    environment:
      - POSTGRES_USER=${APP_CONFIG__DB__USER}
      - POSTGRES_PASSWORD=${APP_CONFIG__DB__PASS}
      - POSTGRES_DB=${APP_CONFIG__DB__NAME}
    ports:
      - "${APP_CONFIG__DB__PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storage-redis:
      image: redis:alpine
      container_name: storage-redis
      restart: always
      environment:
        - REDIS_PASSWORD=${APP_CONFIG__REDIS__PASS}
      command: ["redis-server", "--appendonly", "yes", "--requirepass", "${APP_CONFIG__REDIS__PASS}"]
      
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "${APP_CONFIG__REDIS__PASS}", "ping"]
        interval: 5s
        timeout: 5s
        retries: 3

      ports:
        - "${APP_CONFIG__REDIS__PORT}:6379"
      networks:
        - redis_network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - redis_network
    depends_on:
      - storage-redis
  
  # app-backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   container_name: app-backend
  #   depends_on:
  #     - db-postgres
  #   ports: 
  #     - "8000:8000"
  #   command: >
  #     sh -c "python3 run.py"  



volumes:
  redis_data:
  redis_insight_data:
  postgres_data:

networks:
  redis_network:
    driver: bridge
