"""refresh token model update

Revision ID: 905116d62867
Revises: b398de946933
Create Date: 2025-11-06 13:30:46.712274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905116d62867'
down_revision: Union[str, None] = 'b398de946933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('token', sa.String(), nullable=False))
    op.drop_column('refresh_token', 'hashed_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('hashed_token', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('refresh_token', 'token')
    # ### end Alembic commands ###
